Controllers/RegistrantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CallCenterService.Models;
using CallCenterService.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CallCenterService.Controllers
{
    public class RegistrantController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RegistrantController(DatabaseContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Faults.Include(f => f.Client).ToListAsync());
        }

        public async Task<IActionResult> Opened_faults()
        {
            var faults = from m in _context.Faults
                         select m;
            string ss = "Open";
            if (!String.IsNullOrEmpty(ss))
            {
                faults = faults.Where(s => s.Status.Equals("Open"));
            }
            return View(await faults.ToListAsync());
        }

        public async Task<IActionResult> assigned_faults()
        {
            var faults = from m in _context.Faults
                         select m;
            string ss = "In progress";
            if (!String.IsNullOrEmpty(ss))
            {
                faults = faults.Where(s => s.Status.Equals("In progress"));
            }
            return View(await faults.ToListAsync());
        }

        public async Task<IActionResult> Closed_assigned_faults()
        {
            var faults = from m in _context.Faults
                         select m;
            string ss = "Done";
            if (!String.IsNullOrEmpty(ss))
            {
                faults = faults.Where(s => s.Status.Equals("Done"));
            }
            return View(await faults.ToListAsync());
        }

        public IActionResult FaultsList()
        {
            return RedirectToAction("", "Faults");
        }


        public IActionResult AddFault()
        {
            return RedirectToAction("Create", "Faults");
        }

        [HttpGet]
        public async Task<IActionResult> SetServicer(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vm = new SetServicerRegistrantViewModel
            {
                FaultId = (int)id,
                Servicers = await _userManager.GetUsersInRoleAsync("Serwisant"),
                FaultData = _context.Faults.FirstOrDefault(f => f.FaultId == id)
            };

            if (vm.FaultData == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SetServicer(SetServicerRegistrantViewModel vm)
        {
            var fault = await _context.Faults.FirstOrDefaultAsync(f => f.FaultId == vm.FaultId);

            if(vm.ServicerId == null)
            {
                vm.Servicers = await _userManager.GetUsersInRoleAsync("Serwisant");
                vm.FaultData = fault;

                if (vm.FaultData == null)
                {
                    return NotFound();
                }

                return View(vm);
            }

            var servicer = await _userManager.FindByIdAsync(vm.ServicerId);

            if (ModelState.IsValid == false || servicer == null)
            {
                vm.Servicers = await _userManager.GetUsersInRoleAsync("Serwisant");
                vm.FaultData = fault;

                if (vm.FaultData == null)
                {
                    return NotFound();
                }

                return View(vm);
            }

            else
            {
                using (var transaction = _context.Database.BeginTransaction())
                {
                    fault.Status = "In progress";
                    await _context.SaveChangesAsync();

                    Repair sf = new Repair
                    {
                        Fault = fault,
                        Servicer = servicer
                    };

                    //_context.ServicerFault.RemoveRange(_context.ServicerFault.Where(x => x.IdFault == vm.FaultId));

                    await _context.Repairs.AddAsync(sf);
                    await _context.SaveChangesAsync();

                    transaction.Commit();
                }

                return RedirectToAction("Index");
            }
        }

        public IActionResult AddClients()
        {
            return RedirectToAction("Index", "Clients");
        }
    }
}

Views/Registrant/Closed_assigned_faults.cshtml
@model IEnumerable<CallCenterService.Models.Fault>
@{
    ViewData["Title"] = "Closed_assigned_faults";
}

    <h2>Closed_assigned_faults</h2>



    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ClientDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicationDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClientDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationDate)
                    </td>

                </tr>
            }
        </tbody>
    </table>

Views/Registrant/Index.cshtml
@model IEnumerable<CallCenterService.Models.Fault>

@{
    ViewData["Title"] = "Registrant Panel";
}

<h2>Not Assigned Faults</h2>
<p>
    <a asp-action="assigned_faults">Assigned Faults</a>
</p>
<p>
    <a asp-action="Closed_assigned_faults">Closed Assigned Faults</a>
</p>

<p>
    <a asp-action="Opened_faults">Opened Faults</a>
</p>

<p>
    <br />
    <br />
    <a asp-action="AddFault">Add fault</a>
    <a asp-action="AddClients">Clients</a>
    <a asp-action="FaultsList">All Faults</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client.SecondName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Client.Adress)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClientDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client.SecondName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client.Adress)
                </td>
                <td>
                    <a asp-action="SetServicer" asp-route-id="@item.FaultId">Add Servicer</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Registrant/Opened_faults.cshtml
@model IEnumerable<CallCenterService.Models.Fault>
@{
   ViewData["Title"] = "Opened_faults";
}

    <h2>Opened_faults</h2>


    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ClientDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicationDate)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClientDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationDate)
                    </td>

                </tr>
            }
        </tbody>
    </table>

Views/Registrant/SetServicer.cshtml
@model CallCenterService.ViewModels.SetServicerRegistrantViewModel

<h2>Set Servicer</h2>

<h3>Fault: @Model.FaultData.FaultId @Model.FaultData.ClientDescription @Model.FaultData.Status</h3>

<div asp-validation-summary="All"></div>
<form asp-controller="Registrant" asp-action="SetServicer">
    <input asp-for="FaultId" type="hidden" />
    <div><input type="submit" value="Set Servicer" /></div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Servicer Id
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Specialization
                </th>
                <th>
                    Option
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var servicer in Model.Servicers)
            {
                <tr>
                    <td>@servicer.Id</td>
                    <td>@servicer.FirstName</td>
                    <td>@servicer.LastName</td>
                    <td>@servicer.Specialization</td>
                    <td><input asp-for="ServicerId" value="@servicer.Id" type="radio" /></td>
                </tr>
            }
        </tbody>
    </table>
</form>

Views/Registrant/assigned_faults.cshtml
@model IEnumerable<CallCenterService.Models.Fault>
@{
    ViewData["Title"] = "assigned_faults";
}

<h2>Assigned Faults</h2>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClientDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationDate)
                </td>
              
            </tr>
        }
    </tbody>
</table>